const baseUrl =
  process.env.NODE_ENV === 'development'
    ? 'http://localhost:3000/'
    : 'https://api.tamilanexpress.com/';

export const contact = {
  phone: '+1-1001-234-5678',
  email: 'hello@tamilanexpress.com',
  address: '126, select ave - unit 3 scarborough on, m1v 3y6, ontario, canada.',
  openHours: {
    weekdays:'Mon-Fri: 08:00 - 20:00',
    weekend:'Mon-Fri: 08:00 - 20:00'
  }
}
    
export const products = [
  {
    id:'001',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'002',
    category: 'Dairy and Milk',
    name: 'Nestamolt',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '0',
  },
  {
    id:'003',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'004',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'005',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'006',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'007',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'008',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'009',
    category: 'Dairy and Milk',
    name: 'Anchor',
    img:'https://cdn2.webdamdb.com/md_IRLcaRTbLgZ1.png?1517915165',
    alt: 'anchor image',
    weight: '400g',
    maxQty:'10',
    qty:'0',
    tamil: '',
    price: '100',
    discount: '40',
  },

];
