const baseUrl =
  process.env.NODE_ENV === 'development'
    ? 'http://localhost:3000/'
    : 'https://api.tamilanexpress.com/';
export const products = [
  {
    id:'001',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'002',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'003',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'004',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'005',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'006',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'007',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'008',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },
  {
    id:'009',
    category: 'Dairy and Milk',
    name: 'Anchor',
    alt: 'anchor image',
    weight: '400g',
    tamil: '',
    price: '40.50',
    discount: '40',
  },

];
